### ISSUE TITLE
Aesthetic suggestion

### ISSUE THREAD

**Issue by aksr** [phonologus/QED#12]
Many of `man 7` pages don't have synopsis. It's entirely unneccessary, and also, the name could be improved. 
I suggest removing synopsis completely and removing `qed-tutorial -` from `NAME` 
(`Programming in Qed: A Tutorial` is enough).

**Comment by phonologus** [comment]
Yes, I agree. The manpage format version is generated by `asciidoctor`, and it stupidly insists on a SYNOPSIS section, and requires the NAME section to be in the specific `program name - short description' format (so that it can parse it).

I'll write a quick post-processing script to make the changes and get it into the Makefile pipeline.

**Comment by aksr** [comment]
Thank you.
