### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by leahneukirchen** [phonologus/QED#7]
I'm not sure we want to fix this for historical preservation, but the `qed-tutorial.pdf` is wrong about chaining arithmetic operations:
It says the syntax is `za#:4#*-5#p`.  However, the correct syntax (also documented in the man page) is `za#:4*-5p`, i.e. no repetition of `#`.

**Comment by phonologus** [comment]
I'm open to suggestions about the historical documentation in general. I am instinctively a bit of an archaeoloist, and hate changing artifacts that I didn't create myself. However, having documentation that does not accurately describe QED as it now is, is clearly unhelpful. This is especially so now that there is possibly a handful of end-users who are more interested in QED as a productivity tool, rather than an interesting exercise in software necromancy!

The right thing to do would be to archive the historical documentation for the record, and then update it to describe the present incarnation of QED. I'm happy to do this (tho' admit I have been putting it off!).

Perhaps we can keep this thread open while I get started, so that you (and anyone else listening in) can continue to contribute corrections as you find them?

**Comment by phonologus** [comment]
I've almost finished a thorough editing and updating of the tutorial, which I've also turned into Markdown.
It turns out that the whole section on registers is extremely out of date, and looks like it was hastily written. I've had to rewrite a lot of it for the updated syntax found in this Qed, and I've amplified many of the examples to make them clearer.
Mercifully, the manpage seems to be pretty much up-to-date as far as language features go, so it has been reasonably straightforward (if a little laborious) to bring the tutorial into line.
Hopefully I'll be able to push the updated tutorial later this week.

**Comment by phonologus** [comment]
The tutorial re-write is done and pushed.

All the old, and new, examples are now in sync with this current incarnation of Qed.

A brand new tutorial for a modern audience would be a nice thing to have: introduction to
line-oriented editing; Unicode; relevant examples (streamlining a `git` work-flow, for instance). And pretty typesetting.

No promises, but I'm off to learn `asciidoc`....

I'm closing this issue now. Any comments/suggestions/corrections for the updated tutorial, please start a new issue.
